version: "3.9"

services:
  pioneer:
    build: .
    container_name: pioneer
    restart: no
    network_mode: "host"
    env_file: .env
    # user: ${UGID}
    environment:
      - "DISPLAY"
      - "QT_X11_NO_MITSHM=1"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      # - /etc/group:/etc/group:ro
      # - /etc/passwd:/etc/passwd:ro
      # - /etc/shadow:/etc/shadow:ro
      # - /etc/sudoers:/etc/sudoers:ro
      # - /etc/sudoers.d:/etc/sudoers.d:ro
      # - /home/csrobot:/home/csrobot:rw
    # devices:
    #   - ${PIONEER_DEVICE}:/dev/ttyUSB0
    #   - ${FRONT_LIDAR_DEVICE}:/dev/ttyACM0
      # - ${REAR_LIDAR_DEVICE}:/dev/ttyACM1
    # tty: true # only for debug
    # stdin_open: true # only for debug
  